# -*- coding: utf-8 -*-
"""Catalogo de Zonas Metropolitanas (delimitacion Metropolis de Mexico 2020)."""

ZONAS = {
    "ZM Guadalajara": {"JALISCO": ["GUADALAJARA","JUANACATLÁN","EL SALTO","TLAJOMULCO DE ZÚÑIGA","SAN PEDRO TLAQUEPAQUE","TONALÁ","ZAPOPAN"]},
    "Tepatitlán": {"JALISCO": ["TEPATITLÁN DE MORELOS"]},
    "ZM Saltillo": {"COAHUILA": ["ARTEAGA","RAMOS ARIZPE","SALTILLO"]},
    "MM Matamoros": {"TAMAULIPAS": ["MATAMOROS"]},
    "ZM Piedras Negras": {"COAHUILA": ["NAVA","PIEDRAS NEGRAS"]},
    "ZM La Laguna": {"COAHUILA": ["MATAMOROS","TORREÓN"], "DURANGO": ["GÓMEZ PALACIO","LERDO"]},
    "ZM Monclova-Frontera": {"COAHUILA": ["CASTAÑOS","FRONTERA","MONCLOVA","SAN BUENAVENTURA"]},
    "ZM Reynosa": {"TAMAULIPAS": ["REYNOSA","RÍO BRAVO"]},
    "ZC Sabinas": {"COAHUILA": ["SABINAS","SAN JUAN DE SABINAS"]},
    "ZM Cuernavaca": {"MORELOS": ["CUERNAVACA","EMILIANO ZAPATA","HUITZILAC","JIUTEPEC","TEMIXCO","TEPOZTLÁN","XOCHITEPEC","YAUTEPEC","COATETELCO","XOXOCOTLA"]},
    "MM Hermosillo": {"SONORA": ["HERMOSILLO"]},
    "ZM Toluca": {"MÉXICO": ["ALMOLOYA DE JUÁREZ","CALIMAYA","CHAPULTEPEC","LERMA","METEPEC","MEXICALTZINGO","OCOYOACAC","OTZOLOTEPEC","RAYÓN","SAN ANTONIO LA ISLA","SAN MATEO ATENCO","TEMOAYA","TENANGO DEL VALLE","TOLUCA","XONACATLÁN","ZINACANTEPEC"]},
    "ZM Pachuca": {"HIDALGO": ["MINERAL DEL MONTE","PACHUCA DE SOTO","MINERAL DE LA REFORMA","ZAPOTLÁN DE JUÁREZ","ZEMPOALA"]},
    "ZM Ciudad de México": {
        "CIUDAD DE MÉXICO": ["ÁLVARO OBREGÓN","AZCAPOTZALCO","BENITO JUÁREZ","COYOACÁN","CUAJIMALPA DE MORELOS","CUAUHTÉMOC","GUSTAVO A. MADERO","IZTACALCO","IZTAPALAPA","LA MAGDALENA CONTRERAS","MIGUEL HIDALGO","MILPA ALTA","TLÁHUAC","TLALPAN","VENUSTIANO CARRANZA","XOCHIMILCO"],
        "MÉXICO": ["ACOLMAN","ATENCO","ATIZAPÁN DE ZARAGOZA","COACALCO DE BERRIOZÁBAL","COCOTITLÁN","COYOTEPEC","CUAUTITLÁN","CHALCO","CHIAUTLA","CHICOLOAPAN","CHICONCUAC","CHIMALHUACÁN","ECATEPEC DE MORELOS","HUEHUETOCA","HUIXQUILUCAN","ISIDRO FABELA","IXTAPALUCA","JALTENCO","JILOTZINGO","MELCHOR OCAMPO","NAUCALPAN DE JUÁREZ","NEZAHUALCÓYOTL","NEXTLALPAN","NICOLÁS ROMERO","PAPALOTLA","LA PAZ","SAN MARTÍN DE LAS PIRÁMIDES","TECÁMAC","TEMAMATLA","TEMASCALAPA","TENANGO DEL AIRE","TEOLOYUCAN","TEOTIHUACÁN","TEPETLAOXTOC","TEPOTZOTLÁN","TEXCOCO","TEZOYUCA","TLALMANALCO","TLALNEPANTLA DE BAZ","TULTEPEC","TULTITLÁN","ZUMPANGO","CUAUTITLÁN IZCALLI","VALLE DE CHALCO SOLIDARIDAD","TONANITLA"],
        "HIDALGO": ["ATOTONILCO DE TULA","TIZAYUCA"]},
    "ZM Puebla-Tlaxcala": {
        "PUEBLA": ["ACAJETE","AMOZOC","CORONANGO","CUAUTLANCINGO","JUAN C. BONILLA","OCOYUCAN","PUEBLA","SAN ANDRÉS CHOLULA","SAN GREGORIO ATZOMPA","SAN MIGUEL XOXTLA","SAN PEDRO CHOLULA","TEPATLAXCO DE HIDALGO","TLALTENANGO"],
        "TLAXCALA": ["ACUAMANALA DE MIGUEL HIDALGO","MAZATECOCHCO DE JOSÉ MARÍA MORELOS","PAPALOTLA DE XICOHTÉNCATL","SAN JERÓNIMO ZACUALPAN","SAN JUAN HUACTZINCO","SAN LORENZO AXOCOMANITLA","SAN PABLO DEL MONTE","SANTA CATARINA AYOMETLA","SANTA CRUZ QUILEHTLA","TENANCINGO","TEOLOCHOLCO","TEPEYANCO","TETLATLAHUCA","XICOHTZINCO","ZACATELCO"]},
}

def pares_zona():
    """[(zona, estado, municipio), ...]"""
    return [(z, e, m) for z, d in ZONAS.items() for e, ms in d.items() for m in ms]
